name: Development Workflow #ensure code is working before previewing deployment

on: 
  pull_request:
    types: [closed]
    branches:
      - dev # Trigger only when pull request is merged into the Dev branch.
  workflow_dispatch:

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js (stable version)
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'  # Using stable version of node
    
    - name: npm install, test and build
      run: |
        npm install 
        npm test
        npm run build

  merge-to-staging:
    environment: Staging
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout Staging branch
      uses: actions/checkout@v4
      with:
        ref: staging  # Explicitly checkout the staging branch

    - name: Fetch the Dev branch
      run: git fetch origin dev  # Fetch the Dev branch

    - name: Merge Dev into Staging
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git merge origin/dev --allow-unrelated-histories -m "Merge from Dev to Staging"

    - name: Push code to Staging
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
