name: Development Workflow #ensure code is working before previewing deployment

on: 
  pull_request:
    branches:
      - Dev # Trigger only when pull request is merged into the staging branch.
  workflow_dispatch:

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js (latest version)
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'  # Using stable version of node
    
    - name: npm install, test and build
      run: |
        npm install 
        npm test
        npm run build

  deploy-to-staging:
    environment: Staging
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Push code to staging
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git remote add staging https://github.com/MarshPeter/swe40006-assign.git
        git fetch staging
        git checkout staging
        git merge --no-ff dev -m "Merge from dev to staging"
        git push staging HEAD:staging
