name: Staging to Production

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy-to-deployment:
    environment: Staging
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create pull request
        run: gh pr create --base main --head staging --title 'Merge staging into main' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}