name: Staging to Production

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy-to-deployment:
    environment: Staging
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js (latest version)
        uses: actions/setup-node@v4

      # Create Pull Request from Staging to Main
      - name: Create Pull Request from Staging to Main
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging  # Source branch (staging)
          base: main       # Target branch (main)
          title: "Automated PR: Merge Staging into Main"
          body: "This PR merges changes from staging into the main branch."
          labels: |
            automated-pr