name: Staging to Production

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy-to-deployment:
    environment: Production
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to Vercel Action
      uses: BetaHuhn/deploy-to-vercel-action@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        PRODUCTION: false # Don't deploy to production environment
