name: Staging to Production

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy-to-deployment:
    environment: Staging
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push changes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (latest version)
        uses: actions/setup-node@v4
        with:
          node-version: 'node'  # Use the latest stable version of Node.js

      - name: Create PR to production
        run: |
          git checkout staging
          git remote add origin https://github.com/MarshPeter/swe40006-assign.git
          git checkout -b production-merge
          git push origin production-merge
          
          gh pr create --title "Deploy to Production" --body "Requesting deployment from staging to production" --base main --head production-merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}